### ISSUE TITLE
Create and configure Build stage

### ISSUE THREAD

**Issue by alex-s-hong** [Products-Squad/products#147]
**As a developer,** 
**I need a build stage with unit-test job**  
**So that any updates can be assured to be reliable before goes to the next stage.**  

**Assumptions:** 
* Toolchain on the cloud
* Nosetests

**Acceptance Criteria:**
```
Given build stages on pipeline with nosetests ,
When developer commit to the master branch,
Then it will trigger build stages on pipeline and pass unittest.
```

**Comment by ianchou19** [comment]
@alex-s-hong  
Since we use your account to creat continous delivery pipeline in IBM Cloud but you are not the owner of our Product GitHub repo, thus I faced the below issue when I was trying to create the build stage of our toolchains. (as below pic)

<img width="1410" alt="螢幕快照 2019-12-02 上午10 50 43" src="https://user-images.githubusercontent.com/11553721/69973744-05ca3300-14f2-11ea-84d3-db68a1dd6852.png">

I think I can transfer our repositories to your GitHub accounts since I'm the current owner of it.
